EIMS/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from user import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', user_views.homepage, name='root'),
    path('search_human/', user_views.search_human, name='search_human'),
    path('statistic/', user_views.statistic, name='statistic'),
    path('distribute/<str:industry>/<str:province>/', user_views.distribute, name='distribute'),
    path('register/', user_views.register, name='register'),
    path('login/', user_views.login, name='login'),
    path('logout/', user_views.logout, name='logout'),
    path('profile/', user_views.profile, name='profile'),
    path('bind/', user_views.bind, name='bind'),
    path('modify/', user_views.modify, name='modify'),
    path('captcha/', include('captcha.urls')),
    path('company/', include('company.urls')),
    path('human/', include('human.urls')),
]

company/urls.py
from django.urls import path
from . import views


app_name = 'company'
urlpatterns = [
    path('search/<str:name>/'
         '<str:province>/<str:industry>/<str:capital>/<str:company_type>/<str:operating_status>/'
         '<int:page>/',
         views.search_company, name='search'),
    path('<int:pk>/', views.company_detail, name='detail'),
]

human/urls.py
from django.urls import path
from . import views


app_name = 'human'
urlpatterns = [
    path('search/<str:name>/<str:position>/<int:page>/', views.search_human, name='search'),
    path('<str:name>/', views.human, name='detail'),
]

company/models.py
from django.db import models


class Company(models.Model):
    uniform_social_credit_code = models.CharField('统一社会信用代码', max_length=18)
    name = models.CharField('企业名称', max_length=128)
    registered_capital = models.IntegerField('注册资本', db_index=True, null=True)
    paid_up_capital = models.IntegerField('实缴资本', null=True)
    business_scope = models.CharField('经营范围', max_length=1024, null=True)
    industry = models.CharField('所属行业', max_length=128, db_index=True, null=True)
    tel = models.CharField('电话', max_length=64, null=True)
    email = models.EmailField('邮箱', null=True)
    province = models.CharField('省', max_length=32, db_index=True, null=True)
    city = models.CharField('市', max_length=32, null=True)
    district = models.CharField('县/区', max_length=32, null=True)
    detail_address = models.CharField('详细地址', max_length=128, null=True)
    company_type = models.CharField('企业类型', max_length=128, null=True)
    business_registration_number = models.CharField('工商注册号', max_length=14, null=True)
    registration_authority = models.CharField('登记机关', max_length=128, null=True)
    operating_status = models.CharField('经营范围', max_length=64, null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '企业基础信息'
        verbose_name_plural = '企业基础信息'


class Change(models.Model):
    company = models.ForeignKey('Company', verbose_name='所属企业', on_delete=models.CASCADE)
    change_date = models.DateField('变更时间')
    change_item = models.CharField('变更项目', max_length=256)
    before_change = models.CharField('变更前', max_length=1024)
    after_change = models.CharField('变更后', max_length=1024)
    create_date = models.DateField('创建时间', auto_now_add=True)

    def __str__(self):
        return self.company.name + ' ' + self.change_item

    class Meta:
        verbose_name = '企业变更信息'
        verbose_name_plural = '企业变更信息'


class Trademark(models.Model):
    id = models.CharField(max_length=16, primary_key=True)
    company = models.ForeignKey('Company', verbose_name='所属企业', on_delete=models.CASCADE)
    image_url = models.URLField('商标')
    name = models.CharField('商标名称', max_length=128)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '商标注册'
        verbose_name_plural = '商标注册'


class Classification(models.Model):
    trademark = models.ForeignKey('Trademark', verbose_name='商标名称', on_delete=models.CASCADE)
    classification = models.CharField('国际分类', max_length=64)
    process = models.CharField('商标流程', max_length=64)
    status = models.CharField('商标状态', max_length=16)

    def __str__(self):
        return self.trademark.name + ' ' + self.classification

    class Meta:
        verbose_name = '商标分类信息'
        verbose_name_plural = '商标分类信息'

human/models.py
from django.db import models


class Serving(models.Model):
    company = models.ForeignKey('company.Company', verbose_name='所属企业', on_delete=models.CASCADE)
    human_name = models.CharField('姓名', max_length=32, db_index=True)
    position = models.CharField('职位', max_length=32)

    def __str__(self):
        return self.human_name

    class Meta:
        verbose_name = '主要人员'
        verbose_name_plural = '主要人员'

company/forms.py
from django import forms
from .models import Company, Change, Trademark, Classification


class CompanyForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = '__all__'
        labels = {
            'uniform_social_credit_code': '统一社会信用代码',
            'name': '企业名称',
            'registered_capital': '注册资本',
            'paid_up_capital': '实缴资本',
            'business_scope': '经营范围',
            'industry': '所属行业',
            'tel': '电话',
            'email': '邮箱',
            'province': '省',
            'city': '市',
            'district': '县/区',
            'detail_address': '详细地址',
            'company_type': '企业类型',
            'business_registration_number': '工商注册号',
            'registration_authority': '登记机关',
            'operating_status': '经营状态',
        }
        widgets = {
            'uniform_social_credit_code': forms.TextInput(attrs={'class': 'form-control'}),
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'registered_capital': forms.TextInput(attrs={'class': 'form-control'}),
            'paid_up_capital': forms.TextInput(attrs={'class': 'form-control'}),
            'business_scope': forms.TextInput(attrs={'class': 'form-control'}),
            'industry': forms.TextInput(attrs={'class': 'form-control'}),
            'tel': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'province': forms.TextInput(attrs={'class': 'form-control'}),
            'city': forms.TextInput(attrs={'class': 'form-control'}),
            'district': forms.TextInput(attrs={'class': 'form-control'}),
            'detail_address': forms.TextInput(attrs={'class': 'form-control'}),
            'company_type': forms.TextInput(attrs={'class': 'form-control'}),
            'business_registration_number': forms.TextInput(attrs={'class': 'form-control'}),
            'registration_authority': forms.TextInput(attrs={'class': 'form-control'}),
            'operating_status': forms.TextInput(attrs={'class': 'form-control'}),
        }

company/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.shortcuts import get_object_or_404
from .models import Company
from django.db.models import Q


entry_per_page = 20


def search_company(request, name, province, industry, capital, company_type, operating_status, page):
    if request.method == 'GET' and name:
        query = Q(name__contains=name)
        if province != '不限':
            query &= Q(province=province)
        if industry != '不限':
            query &= Q(industry=industry)
        if capital != '不限':
            capital = int(capital)
            print(capital)
            if capital == 0:
                query &= Q(registered_capital__lt=100)
            elif capital == 1:
                query &= Q(registered_capital__gte=100) & Q(registered_capital__lt=200)
            elif capital == 2:
                query &= Q(registered_capital__gte=200) & Q(registered_capital__lt=500)
            elif capital == 3:
                query &= Q(registered_capital__gte=500) & Q(registered_capital__lt=1000)
            elif capital == 4:
                query &= Q(registered_capital__gte=1000)
        if company_type != '不限':
            query &= Q(company_type=company_type)
        if operating_status != '不限':
            query &= Q(operating_status=operating_status)
        total_company_list = Company.objects.filter(query)
        company_count = total_company_list.count()
        total_page = (company_count + entry_per_page - 1) // entry_per_page
        page = max(min(page, total_page), 1)
        company_list = total_company_list[(page - 1) * entry_per_page: page * entry_per_page]
        pre_page, next_page = page - 1, page + 1
        if total_page < 5:
            page_list = list(range(1, total_page + 1))
        else:
            left, right = page - 1, total_page - page
            left, right = min(left, 2 + max(0, 2 - right)), min(right, 2 + max(0, 2 - left))
            page_list = list(range(page - left, page + right + 1))
        return render(request, 'search_company.html', locals())
    else:
        return redirect('/')


def company_detail(request, pk):
    company = get_object_or_404(Company, pk=pk)
    model = Company
    return render(request, 'company.html', locals())

company/templates/company.html
{% extends 'base.html' %}

{% load static %}
{% block css %}<link href="{% static 'css/company.css' %}" rel="stylesheet">{% endblock %}

{% block title %}{{ company.name }}{% endblock %}

{% block body %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                企业基本信息
            </div>

            <div class="panel-body">
                <table class="table table-bordered company_info">
                    <tbody>
                        <tr>
                            <th>统一社会信用代码</th>
                            <td>{{ company.uniform_social_credit_code }}</td>
                            <th>企业名称</th>
                            <td>{{ company.name }}</td>
                        </tr>
                        <tr>
                            <th>注册资本</th>
                            <td>
                                {% if company.registered_capital %}
                                    {{ company.registered_capital }}万元
                                {% endif %}
                            </td>
                            <th>实缴资本</th>
                            <td>
                                {% if company.paid_up_capital %}
                                    {{ company.paid_up_capital }}万元
                                {% endif %}
                            </td>
                        </tr>
                        <tr>
                            <th>企业类型</th>
                            <td>{{ company.company_type }}</td>
                            <th>所属行业</th>
                            <td>{{ company.industry }}</td>
                        </tr>
                        <tr>
                            <th>电话</th>
                            <td>{{ company.tel }}</td>
                            <th>邮箱</th>
                            <td>{{ company.email }}</td>
                        </tr>
                        <tr>
                            <th>地址</th>
                            <td>
                                {% if company.province != company.city %}{{ company.province }}{% endif %}{{ company.city }}{{ company.district }}{{ company.detail_address }}
                            </td>
                            <th>经营状态</th>
                            <td>{{ company.operating_status }}</td>
                        </tr>
                        <tr>
                            <th>工商注册号</th>
                            <td>{{ company.business_registration_number }}</td>
                            <th>登记机关</th>
                            <td>{{ company.registration_authority }}</td>
                        </tr>
                        <tr>
                            <th>经营范围</th>
                            <td colspan="3">{{ company.business_scope }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading">
                主要人员
            </div>

            <div class="panel-body">
                <table class="table table-bordered">
                    <thead>
                        <th>姓名</th>
                        <th>职位</th>
                    </thead>

                    <tbody>
                        {% for serving_item in company.serving_set.all %}
                            <tr>
                                <td>
                                    <a href="{% url 'human:detail' serving_item.human_name %}">
                                        {{ serving_item.human_name }}
                                    </a>
                                </td>
                                <td>{{ serving_item.position }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading">
                注册商标
            </div>

            <div class="panel-body">
                <table class="table table-bordered">
                    <thead>
                        <th>商标</th>
                        <th>商标名称</th>
                        <th>注册号</th>
                        <th>国际分类</th>
                        <th>商标流程</th>
                        <th>商标状态</th>
                    </thead>

                    <tbody>
                        {% for trademark_item in company.trademark_set.all %}
                            {% for classification_item in trademark_item.classification_set.all %}
                                <tr>
                                    <td><img width="50px" src="{{ trademark_item.image_url }}" /></td>
                                    <td>{{ trademark_item.name }}</td>
                                    <td>{{ trademark_item.id }}</td>
                                    <td>{{ classification_item.classification }}</td>
                                    <td>{{ classification_item.process }}</td>
                                    <td>{{ classification_item.status }}</td>
                                </tr>
                            {% endfor %}
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading">
                企业变更信息
            </div>

            <div class="panel-body">
                <table class="table table-bordered change_info">
                    <thead>
                        <th>变更日期</th>
                        <th>变更项目</th>
                        <th>变更前</th>
                        <th>变更后</th>
                        <th>创建日期</th>
                    </thead>

                    <tbody>
                        {% for change_item in company.change_set.all %}
                            <tr>
                                <td>{{ change_item.change_date }}</td>
                                <td>{{ change_item.change_item }}</td>
                                <td>{{ change_item.before_change }}</td>
                                <td>{{ change_item.after_change }}</td>
                                <td>{{ change_item.create_date }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

company/templates/search_company.html
{% extends 'base.html' %}

{% block title %}搜索结果{% endblock %}

{% block body %}
    <div class="container">
        <h3>搜索结果：</h3>
        <div class="panel panel-default">
            <div class="panel-heading">
                共找到{{ company_count }}家公司
            </div>

            <div class="panel-body">
                <div class="btn-group-vertical btn-block" role="group">
                    {% for company in company_list %}
                        <a href="{% url 'company:detail' company.id %}" class="btn btn-default btn-block btn-lg">
                            {{ company.name }}
                        </a>
                    {% endfor %}
                </div>
                <nav class="text-center">
                    <ul class="pagination pagination-lg">
                        <li {% if page == 1 %}class="disabled"{% endif %}>
                            <a {% if page != 1 %}href="{% url 'company:search' name province industry capital company_type operating_status pre_page %}{% endif %}">
                                <span>&laquo;</span>
                            </a>
                        </li>
                        {% for i in page_list %}
                            <li {% if i == page %}class="active"{% endif %}>
                                <a href="{% url 'company:search' name province industry capital company_type operating_status i %}">
                                    {{ i }}
                                </a>
                            </li>
                        {% endfor %}
                        <li {% if page == total_page %}class="disabled"{% endif %}>
                            <a {% if page != total_page %}href="{% url 'company:search' name province industry capital company_type operating_status next_page %}"{% endif %}>
                                <span>&raquo;</span>
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
{% endblock %}