EIMS/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from user import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', user_views.homepage, name='root'),
    path('search_human/', user_views.search_human, name='search_human'),
    path('statistic/', user_views.statistic, name='statistic'),
    path('distribute/<str:industry>/<str:province>/', user_views.distribute, name='distribute'),
    path('register/', user_views.register, name='register'),
    path('login/', user_views.login, name='login'),
    path('logout/', user_views.logout, name='logout'),
    path('profile/', user_views.profile, name='profile'),
    path('bind/', user_views.bind, name='bind'),
    path('modify/', user_views.modify, name='modify'),
    path('captcha/', include('captcha.urls')),
    path('company/', include('company.urls')),
    path('human/', include('human.urls')),
]

company/urls.py
from django.urls import path
from . import views


app_name = 'company'
urlpatterns = [
    path('search/<str:name>/'
         '<str:province>/<str:industry>/<str:capital>/<str:company_type>/<str:operating_status>/'
         '<int:page>/',
         views.search_company, name='search'),
    path('<int:pk>/', views.company_detail, name='detail'),
]

human/urls.py
from django.urls import path
from . import views


app_name = 'human'
urlpatterns = [
    path('search/<str:name>/<str:position>/<int:page>/', views.search_human, name='search'),
    path('<str:name>/', views.human, name='detail'),
]

human/models.py
from django.db import models


class Serving(models.Model):
    company = models.ForeignKey('company.Company', verbose_name='所属企业', on_delete=models.CASCADE)
    human_name = models.CharField('姓名', max_length=32, db_index=True)
    position = models.CharField('职位', max_length=32)

    def __str__(self):
        return self.human_name

    class Meta:
        verbose_name = '主要人员'
        verbose_name_plural = '主要人员'

human/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from .models import Serving
from django.db.models import Q


entry_per_page = 20


def search_human(request, name, position, page):
    if request.method == 'GET' and name:
        query = Q(human_name__contains=name)
        if position != '不限':
            query &= Q(position=position)
        total_human_list = Serving.objects.filter(query).values_list('human_name').distinct()
        human_count = total_human_list.count()
        total_page = (human_count + entry_per_page - 1) // entry_per_page
        page = max(min(page, total_page), 1)
        human_list = total_human_list[(page - 1) * entry_per_page: page * entry_per_page]
        pre_page, next_page = page - 1, page + 1
        if total_page < 5:
            page_list = list(range(1, total_page + 1))
        else:
            left, right = page - 1, total_page - page
            left, right = min(left, 2 + max(0, 2 - right)), min(right, 2 + max(0, 2 - left))
            page_list = list(range(page - left, page + right + 1))
        return render(request, 'search_human.html', locals())
    else:
        return redirect('/')


def human(request, name):
    serving = Serving.objects.filter(human_name=name)
    return render(request, 'human.html', locals())

human/templates/human.html
{% extends 'base.html' %}

{% block title %}{{ name }}{% endblock %}

{% block body %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                他的商业角色
            </div>

            <div class="panel-body">
                <table class="table table-bordered">
                    <thead>
                        <th>企业名称</th>
                        <th>职位</th>
                    </thead>
                    <tbody>
                        {% for serve in serving %}
                            <tr>
                                <td>
                                    <a href="{% url 'company:detail' serve.company.id %}">
                                        {{ serve.company.name }}
                                    </a>
                                </td>
                                <td>{{ serve.position }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

human/templates/search_human.html
{% extends 'base.html' %}

{% block title %}搜索结果{% endblock %}

{% block body %}
    <div class="container">
        <h3>搜索结果：</h3>
        <div class="panel panel-default">
            <div class="panel-heading">
                共找到{{ human_count }}位相关老板
            </div>

            <div class="panel-body">
                <div class="btn-group-vertical btn-block" role="group">
                    {% for human in human_list %}
                        <a href="{% url 'human:detail' human.0 %}" class="btn btn-default btn-block btn-lg">
                            {{ human.0 }}
                        </a>
                    {% endfor %}
                </div>
                <nav class="text-center">
                    <ul class="pagination pagination-lg">
                        <li {% if page == 1 %}class="disabled"{% endif %}>
                            <a {% if page != 1 %}href="{% url 'human:search' name position pre_page %}{% endif %}">
                                <span>&laquo;</span>
                            </a>
                        </li>
                        {% for i in page_list %}
                            <li {% if i == page %}class="active"{% endif %}>
                                <a href="{% url 'human:search' name position i %}">
                                    {{ i }}
                                </a>
                            </li>
                        {% endfor %}
                        <li {% if page == total_page %}class="disabled"{% endif %}>
                            <a {% if page != total_page %}href="{% url 'human:search' name position next_page %}"{% endif %}>
                                <span>&raquo;</span>
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
{% endblock %}